allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  prisma: true
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/engines"
  - "@swc/core"
  - prisma
